//================================================================================//
//                                     FONT
//================================================================================//
#include "font/opensans12.h"
#include "font/opensans14b.h"
#include "font/opensans16.h" 
#include "font/opensans16b.h"
#include "font/opensans18.h" 
#include "font/opensans18b.h" 
#include "font/opensans20.h"
#include "font/opensans20b.h"
#include "font/opensans24.h"
#include "font/opensans24b.h"
#include "font/opensans26b.h"




//================================================================================//
//                                  images
//================================================================================//
#include "image/charging40.h"
#include "image/sleep.h"
#include "image/tile.h"
#include "image/doubleTile.h"
#include "image/tripleTile.h"
#include "image/quadrupleTile.h"
#include "image/clickMark.h"
#include "image/ApImage.h"
#include "image/wifiSuccessfully.h"
#include "image/whiteHeader.h"
#include "image/halloweenBanner.h"
#include "image/christmasBanner.h"
#include "image/newYearBanner.h"


//================================================================================//
//                                  ICONS
//================================================================================//
//device icons 80x80 px
#include "image/deviceIcons80/door80.h"
#include "image/deviceIcons80/garageDoor80.h"
#include "image/deviceIcons80/gate80.h"
#include "image/deviceIcons80/humidity80.h"
#include "image/deviceIcons80/light80.h"
#include "image/deviceIcons80/pressure80.h"
#include "image/deviceIcons80/rollerShutter80.h"
#include "image/deviceIcons80/thermometer80.h"
#include "image/deviceIcons80/window80.h"
#include "image/deviceIcons80/wirelessPlug80.h"
#include "image/deviceIcons80/lock80.h"
#include "image/deviceIcons80/bathroom80.h"
#include "image/deviceIcons80/bedroom80.h"
#include "image/deviceIcons80/fan80.h"
#include "image/deviceIcons80/garden80.h"
#include "image/deviceIcons80/heater80.h"
#include "image/deviceIcons80/home80.h"
#include "image/deviceIcons80/kitchen80.h"
#include "image/deviceIcons80/logo80.h"
#include "image/deviceIcons80/lounge80.h"
#include "image/deviceIcons80/powerCounter80.h"
#include "image/deviceIcons80/stove80.h"
#include "image/deviceIcons80/swimmingPool80.h"
#include "image/deviceIcons80/waterCounter80.h"
#include "image/deviceIcons80/alarm80.h"
#include "image/deviceIcons80/alarm280.h"
#include "image/deviceIcons80/batteryH80.h"
#include "image/deviceIcons80/batteryV80.h"
#include "image/deviceIcons80/car80.h"
#include "image/deviceIcons80/car280.h"
#include "image/deviceIcons80/climate80.h"
#include "image/deviceIcons80/co80.h"
#include "image/deviceIcons80/co280.h"
#include "image/deviceIcons80/smokeSensor80.h"
#include "image/deviceIcons80/waterPlant80.h"
#include "image/deviceIcons80/waterSensor80.h"
#include "image/deviceIcons80/waterSensor280.h"
#include "image/deviceIcons80/wifi80.h"
#include "image/deviceIcons80/wireless80.h"
#include "image/deviceIcons80/printer80.h"
#include "image/deviceIcons80/lux80.h"
#include "image/deviceIcons80/dollar80.h"
#include "image/deviceIcons80/euro80.h"
#include "image/deviceIcons80/lightbolt80.h"
#include "image/deviceIcons80/washingMachine80.h"
#include "image/deviceIcons80/weather80.h"
#include "image/deviceIcons80/wind80.h"
#include "image/deviceIcons80/openEnvelope80.h"
#include "image/deviceIcons80/closeEnvelope80.h"
#include "image/deviceIcons80/spa80.h"
#include "image/deviceIcons80/octoprint80.h"
#include "image/deviceIcons80/shopping80.h"
#include "image/deviceIcons80/fish.h"
#include "image/deviceIcons80/mad.h"
#include "image/deviceIcons80/fool.h"


//================================================================================//
//                                  Weather icons
//================================================================================//
#include "image/weather/clear.h"
#include "image/weather/clearNight.h"
#include "image/weather/cloudy.h"
#include "image/weather/fog.h"
#include "image/weather/hail.h"
#include "image/weather/logoSmall.h"
#include "image/weather/partlyCloudy.h"
#include "image/weather/rainy.h"
#include "image/weather/rainyCloudy.h"
#include "image/weather/snowy.h"
#include "image/weather/storm.h"
#include "image/weather/stormRainy.h"
#include "image/weather/twoClouds.h"
#include "image/weather/windy.h"